src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class User
{

    

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $FirstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $JobTitle;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $Enabled;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $UpdateAt;

     /**
     * @ORM\OneToMany(targetEntity=Dish::class, mappedBy="User")
     */
    private $Dish;



    public function __construct() {
        // we set up "created"+"modified"
        $this->setCreatedAt(new \DateTime());
        $this->asupps = new ArrayCollection();
        $this->asupp = new ArrayCollection();
    }

    /**
     * @ORM\PreUpdate()
     */
    public function updateModifiedDatetime() {
        // update the modified time
        $this->setUpdatedAt(new \DateTime());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $Username): self
    {
        $this->username = $Username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->Lastname;
    }

    public function setLastname(string $Lastname): self
    {
        $this->Lastname = $Lastname;

        return $this;
    }

    public function getJobTitle(): ?string
    {
        return $this->JobTitle;
    }

    public function setJobTitle(string $JobTitle): self
    {
        $this->JobTitle = $JobTitle;

        return $this;
    }

    public function getEnabled(): ?bool
    {
        return $this->Enabled;
    }

    public function setEnabled(?bool $Enabled): self
    {
        $this->Enabled = $Enabled;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->UpdateAt;
    }

    public function setUpdatedAt(\DateTimeInterface $UpdateAt): self
    {
        $this->UpdateAt = $UpdateAt;

        return $this;
    }

    /**
     * @return Collection|Dish[]
     */
    public function getDish(): Collection
    {
        return $this->Dish;
    }

    public function addDish(Dish $dish): self
    {
        if (!$this->Dish->contains($dish)) {
            $this->Dish[] = $dish;
            $dish->setUser($this);
        }

        return $this;
    }

    public function removeDish(Dish $dish): self
    {
        if ($this->Dish->removeElement($dish)) {
            // set the owning side to null (unless already changed)
            if ($dish->getUser() === $this) {
                $dish>setUser(null);
            }
        }

        return $this;
    }

   
}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\UserRepository;
use App\Repository\CategoryRepository;

class FrontController extends AbstractController
{

     /**
    * @Route("/", name="homepage")
    */
    public function index(): Response
    {
        return $this->render('front/index.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }


    /**
    * @Route("/equipe", methods={"GET"}, name="front_team")
    */
    public function afficherEquipe(UserRepository $userRep): Response
    {
        return $this->render('front/afficherEquipe.html.twig', [
            'users' => $userRep->findAll() ,
        ]);
    }

     /**
    * @Route("/admin/", methods={"GET"}, name="admin_home")
    */
    public function back(): Response
    {
        return $this->render('admin/index.html.twig', [
            'controller_name' => 'AdminController',
        ]);
    }

    /**
    * @Route("/carte", methods={"GET"}, name="front_dishes")
    */
    public function afficherCategory(CategoryRepository $categoryRep): Response
    {
        
        return $this->render('front/afficherCategory.html.twig', [
            'categories' => $categoryRep->findAll() ,
        ]);
    }

    /**
    * @Route("/carte/{index}", methods={"GET"}, requirements={"index"="\d+"}, name="front_dishes__category")
    */
    public function afficherDetailsCategory(CategoryRepository $categoryRep, int $index): Response
    {
        foreach( $categoryRep->findAll() as $category){
            if($category->getId() == $index){
                return $this->render('front/detailCategory.html.twig', [
                    'category' => $category ,
                ]);
            }
        }
       
    }
  
}

templates/front/afficherCategory.html.twig
{% extends 'base.html.twig' %}

{% block title %}Afficher Catégories{% endblock %}

{% block body %}

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Image </th>
                <th scope="col">Nom </th>
                <th scope="col">Nombre de plats </th>
                <th scope="col">Details</th>
            </tr>
        </thead>
        <tbody>
        {% for category in categories %}
            <tr>
                <td>  <img class="image_plat" src="{{category.Image}}" height="36"/></td>
                <td>  {{category.Name}} </td>
                <td>  {{category.Dish.count}} </td>
                <td>
                    <a href="{{ path('front_dishes__category', {'index': category.Id}) }}"> Voir les détails </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/front/afficherEquipe.html.twig
{% extends 'base.html.twig' %}

{% block title %}afficher Equipe{% endblock %}

{% block body %}



  <table class="table">
        <thead>
            <tr>
                <th scope="col">Nom</th>
                <th scope="col">Prénom</th>
                <th scope="col">Email</th>
                <th scope="col">Job</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>   {{user.lastname}}</td>
                <td>  {{user.firstName}}</td>
                <td>  {{user.Email}}</td>
                <td>  {{user.JobTitle}} </td>
            
            </tr>
        {% endfor %}
    </tbody>
    </table>

{% endblock %}

templates/front/detailCategory.html.twig
{% extends 'base.html.twig' %}

{% block title %}Detail Category{% endblock %}

{% block body %}
   
  <table class="table">
        <thead>
            <tr>
              <td>{{category.Name}}  </td>
            </tr>
            <tr>
                <th scope="col">Image </th>
                <th scope="col">Nom </th>
                <th scope="col">Prix </th>
                <th scope="col">Calories </th>
                <th scope="col">Allergenes </th>
            </tr>
        </thead>
        <tbody>
        {% for dish in category.Dish %}
            <tr>
                <td>  <img  src="{{dish.Image}}" height="36"/></td>
                <td>  {{dish.Name}} </td>
                <td>  {{dish.Price}} </td>
                <td>  {{dish.Calories}} </td>
                <td>
                    {% for allerg in dish.allergen %}
                        {{allerg.name}}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </tbody>

        <tr>
            <td>
                <a href="{{ path('front_dishes') }}"> Revenir aux categories </a>
            </td>
        </tr>
    </table>
{% endblock %}

templates/front/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}


{{ parent() }}

{% endblock %}